spring:
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://localhost:5555
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 1. Route pour Eureka
		- id: eureka-dashboard
		          uri: http://localhost:8761
		          predicates:
		            - Path=/eureka/**
		          filters:
		            - RewritePath=/eureka/(?<segment>.*), /$\{segment}
        # 2. Services Métiers
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/client-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: clientService
                fallbackUri: forward:/fallback/client

        - id: produit-service
          uri: lb://PRODUIT-SERVICE
          predicates:
            - Path=/produit-service/**
          filters:
            - StripPrefix=2
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY

        # 3. Services de Paiement
        - id: factureservice
          uri: lb://FACTURESERVICE
          predicates:
            - Path=/facture-service/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Request-Facture, Microservice

        - id: reglement-service
          uri: lb://REGLEMENT-SERVICE
          predicates:
            - Path=/reglement-service/**
          filters:
            - StripPrefix=2
            - AddResponseHeader=X-Response-Reglement, Processed

        # 4. Services Système

        - id: configservice
          uri: lb://config-service
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*), /$\{segment}

        # 5. Fallback Global
        - id: fallback
          uri: forward:/fallback
          predicates:
            - Path=/fallback/**

        # 6. Redirection API Racine
        - id: root-redirect
          uri: http://example.com
          predicates:
            - Path=/
          filters:
            - RedirectTo=302, /swagger-ui.html

server:
  port: 8888

# Configuration Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always